### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by abdullatif143**
entities of project #1

### CODE REVIEW

**Comment by abdullatif143** [comment]
it is add or not

**Comment by Atifkhan44** [comment]
Thanks abdullatif for adding file.

**Comment by Atifkhan44** [comment]
add file

**Review by Atifkhan44 — APPROVED** [review]
Thanks.

**Comment by Atifkhan44** [comment]
Thanks for add file.

**Comment by Atifkhan44** [comment]
add file.

**Comment by Atifkhan44** [comment]
Thanks.

**Comment by Atifkhan44** [comment]
Thanks.

**Review by Atifkhan44 — APPROVED** [review]
Nice work.

**Comment by Atifkhan44** [comment]
Thanks.

**Comment by Atifkhan44** [comment]
add.

**Pull request closed without merging**
